apiVersion: apps/v1
kind: Deployment
metadata:
  name: text-analytics
spec:
  selector:
    matchLabels:
      app: text-analytics
  replicas: 3
  template:
    metadata:
      labels:
        app: text-analytics
    spec:
      containers:
        - name: text-analytics
          image: text-analytics:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7979
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: text-analytics-svc
spec:
  selector:
    app: text-analytics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7979
      name: http
